In [2]:
import tensorflow as tf
import numpy as np

In [41]:
sent = 'eu rejects german call to boycott british lamb'
ents = {0: '[PAD]', 1: 'O', 2: 'B-PER', 3: 'I-PER', 4: 'B-ORG', 5: 'I-ORG', 6: 'B-LOC', 7: 'I-LOC', 8: 'B-MISC', 9: 'I-MISC'}

In [35]:
m = len(sent.split(' ')) # num of tokens
n = len(ents) # num of tags
N_examples = 1

In [36]:
sample_input = [988, 10950, 204, 628, 6, 3938, 215, 5773]
reshaped = tf.reshape(sample_input, shape=[1,-1])
reshaped

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[  988, 10950,   204,   628,     6,  3938,   215,  5773]])>

The output is a N_examplesxMxN matrix where M=the number of input tokens and N=the number of NER tags. The value (i,j) in each row indicates the probability of token - i having a tag - j.

In [37]:
output = np.random.rand(1,m,n)
output

array([[[0.34468628, 0.80317937, 0.66579117, 0.05305431, 0.49835746,
         0.88995676, 0.6064641 , 0.26306298, 0.35156791, 0.5430262 ],
        [0.32984953, 0.36910559, 0.87148974, 0.34292291, 0.64425646,
         0.19633353, 0.719106  , 0.71501065, 0.25435521, 0.20757459],
        [0.67695238, 0.76535915, 0.18131128, 0.3759815 , 0.99965085,
         0.34393323, 0.07102733, 0.68422573, 0.95815428, 0.06405466],
        [0.87347101, 0.80232081, 0.89558135, 0.15227948, 0.61474763,
         0.89918769, 0.89831634, 0.82514498, 0.8344074 , 0.62373339],
        [0.37234642, 0.10387022, 0.50574181, 0.71714311, 0.31852089,
         0.36063196, 0.93720003, 0.87945287, 0.73973907, 0.60217274],
        [0.57948672, 0.51942269, 0.6449795 , 0.61425331, 0.84798737,
         0.42627617, 0.53821621, 0.39777226, 0.66577475, 0.28971717],
        [0.2897944 , 0.605612  , 0.78573487, 0.06983918, 0.98028496,
         0.1373459 , 0.72007207, 0.46240775, 0.08858269, 0.49376208],
        [0.42109362, 0.7238

- np.argmax returns the index of the maximum value

- axis = -1 or 1 -> return max in each row
- axis = None -> return max in flattened array
- axis = 0 -> return max in each column

In [49]:
prediction = np.argmax(output, axis=-1)[0]
prediction

array([5, 2, 4, 5, 6, 4, 4, 8], dtype=int64)

In [50]:
prediction[0]

5

map index of tag to tag name

In [51]:
prediction = [ents[i] for i in prediction]
prediction

['I-ORG', 'B-PER', 'B-ORG', 'I-ORG', 'B-LOC', 'B-ORG', 'B-ORG', 'B-MISC']

In [52]:
sent

'eu rejects german call to boycott british lamb'

output is gibberish since we used a random matrix to demonstrate